### ISSUE TITLE
I need in the second mention obtain the number of book and paragraf

### ISSUE THREAD

**Issue by Carolina1234** [maieul/biblatex-source-division#1]
Hello, I have seen your package and it seems to me to be very useful, but I can`t  that in an appointment of the same author, the same book but different paragraph it appears in the footnote. 
For example: 
![captura de pantalla 2015-07-07 a las 16 56 02](https://cloud.githubusercontent.com/assets/13221651/8549106/2d9fa356-24c9-11e5-8730-73385bead21a.png)In number 4 i need do mention at book 1, 20. But how you can see is not possible, you know any form of do it?

**Comment by maieul** [comment]
I don't understand your question. Could you reformulate it and provides a MWE ?

**Comment by Carolina1234** [comment]
Sorry my english is so bad i work with text of Polibio, Livio, cicerón, etc. I need ever write the book and the paragrafh, for example,  Livio ab urbe condita 1,7 (th is for the first citation)  for the second and others i need this,  livio, op.cit 1,20 ( for example) with your package is posible obtain the first citation but not the second. The fhoto of my first message is do with your package, ser the 1,4 and 5 citation?  Can you see my problem? Can you help me?

**Comment by maieul** [comment]
Your need is possible with my package: I do it everyday.

I think it is because you don't use one of the standard verbose-trad style.

Could you please provides a MWE? (What is a MWE is explained here http://texfaq.org/FAQ-minxampl.html)

**Comment by Carolina1234** [comment]
% !BIB TS-program = biber
  \documentclass{article} 
 \usepackage[spanish]{babel} 
 \usepackage[utf8]{inputenc}
 \usepackage{csquotes}
  \usepackage[style=verbose-trad1,singletitle=false]{biblatex}
  \usepackage{biblatex-source-division}
    \DeclareNameAlias{default}{last-first/first-last}
     \addbibresource{mibiblio.bib} 
    \renewcommand{\appendixname}{Anexos}
\renewcommand{\appendixtocname}{Anexos}
\renewcommand{\appendixpagename}{Anexos}
\usepackage{graphicx}
\usepackage{float}
\usepackage{subfigure}
 \usepackage{times} 
 \usepackage{setspace}
  \onehalfspace
     \begin{document}
    \renewcommand{\refname}{OBRAS CONSULTADAS}  
     \section {INTRODUCCIÓN}
Aliquam vel tellus ut massa viverra pharetra\footcite[(1,13)]  {Livio:ab}  . Praesent porttitor, elit et consectetuer vulputate\footcite{Alfoldy:1984qd}, orci sem pellentesque ipsum, vitae feugiat orci ante at felis\footcite[(1,100)]{Livio:ab} . Vestibulum velit turpis, cursus id, convallis ac, fringilla non, justo. Maecenas viverra nunc id tortor sollicitudin facilisis.  \footcite[(1,17)]{Livio:ab}.
     \printbibheading
 \printbibliography[keyword=fuentes,heading=subbibliography, title={FUENTES}]
\printbibliography [keyword=modernos,heading=subbibliography, title={BIBLIOGRAFÍA}]

```
 \end{document}
```

This is my code, and the result is: 
![captura de pantalla 2015-07-07 a las 19 52 46](https://cloud.githubusercontent.com/assets/13221651/8553163/d250aaf4-24e1-11e5-9bc6-40186ebea76c.png)

I need in the second and the consecutive citation for live or other autor this:
Livio. op.cit 1, 100 (for exemple)

**Comment by maieul** [comment]
can I also obtain the .bib file?

**Comment by Carolina1234** [comment]
of course 
@book{Apiano:1985aa,
    Author = {Apiano},
    Date-Added = {2015-06-16 23:31:44 +0000},
    Date-Modified = {2015-07-05 01:11:55 +0000},
    Keywords = {modernos},
    Publisher = {Editorial Gredos},
    Title = {Historia Romana},
    Translator = {Sancho Royo, A.},
    Volume = {II},
    Volumetitle = {GUERRAS CIVILES GUERRAS (LIBROS I Y II)},
    Year = {1985}}
@article{balbo2013sulle,
    Author = {Balbo, Mattia},
    Date-Added = {2015-06-15 23:36:32 +0000},
    Date-Modified = {2015-07-05 01:00:42 +0000},
    Journal = {HISTORIKA Studi di storia greca e romana},
    Keywords = {modernos},
    Pages = {13--32},
    Title = {Sulle orme dei Gracchi: L. Apuleio Saturnino e la Transpadana},
    Volume = {2},
    Year = {2013}}@book{Livio:ab,
    Author = {Livio},
    Booktitle = {Ab Urbe Condita},
    Date-Added = {2015-03-11 16:48:23 +0000},
    Date-Modified = {2015-07-05 01:10:35 +0000},
    Editor = {2013.},
    Keywords = {fuentes},
    Series = {XXXI-XLV},
    Title = {Ab Urbe Condita},
    Translator = {Duarte Sanchez, A.D.},
    Volume = {3}}
@book{:2015aa,
    Author = {Livio},
    Date-Added = {2015-03-11 16:45:28 +0000},
    Date-Modified = {2015-07-05 01:00:19 +0000},
    Keywords = {fuentes},
    Series = {XXI-XXX},
    Title = {Ab Urbe Condita},
    Translator = {Duarte Sanchez, A.D.},
    Volume = {II},
    Year = {2013}}
Is not all, i have 93 entries in the bib.file

**Comment by maieul** [comment]
I was requesting for the entry you effectively use in your MWE. FOr example Alfody

**Comment by maieul** [comment]
please try the branch "issue1":
- download https://github.com/maieul/biblatex-source-division/archive/issue1.zip
- unzip it
- push the .sty along your .tex file
- make feedback after running again your .tex file

**Comment by Carolina1234** [comment]
I have the package charged in my document,i  must be doing something badI am not a nuisance any more, thank you for everything.

**Comment by maieul** [comment]
sorry? what does your test do?

**Comment by Carolina1234** [comment]
Really I think that I am not expressing good, i need my first cite for the ancient authors this 
![captura de pantalla 2015-07-07 a las 22 15 45](https://cloud.githubusercontent.com/assets/13221651/8556209/d685e9d6-24f5-11e5-915b-4ee40f9ad190.png) but in the consecutive cites i need this 
![captura de pantalla 2015-07-07 a las 22 17 07](https://cloud.githubusercontent.com/assets/13221651/8556225/f38a3c30-24f5-11e5-9687-aed33779e47d.png) whit your package i obtain one correct numeration for the cite. \cite[(1,7)]{livio} this list your command not? Good, wen i used this command for the second change \cite[(1,10)]{livio} ( the number of paragraph change) i obtain Livio, op.cit but without number. Do not be, if I have  myself understand this time, if  is not like that, forgive me but my english is very bad.

**Comment by maieul** [comment]
Yes, I have understood your need. I told you just to try the new version of the package. With this version, I can obtain
![capture d ecran 2015-07-07 a 22 30 11](https://cloud.githubusercontent.com/assets/636640/8556543/ffbce2f8-24f7-11e5-933e-00ce454a00a2.png)

So please
- download https://github.com/maieul/biblatex-source-division/archive/issue1.zip
- unzip it
- push the .sty along your .tex file
- make feedback after running again your .tex file

Ps: maybe it will be simplier if i write in French and you answer in Spanish?

**Comment by Carolina1234** [comment]
si, por favor, vale  mi texlive tiene una distribución de su paquete, que yo diría que es el mismo que me acaba de enviar, a lo mejor no, estoy intentando encontrar en que lugar de mi distribución poner el que usted amablemente me ha enviado y no se muy bien donde ubicarlo, utilizo la distribución de latex para Mac.

**Comment by maieul** [comment]
placez le fichier .sty juste � c�t� de votre fichier .tex. Cela devrait suffire pour faire le test. Ensuite si le texte est positif, j'enverrai le fichier sur le CTAN et il vous suffira d'utiliser texlive utility pour mettre � jour.

**Comment by Carolina1234** [comment]
Perfecto, muchísimas gracias, de verdad, me acaba de ahorrar horas y horas de hacer referencias a mano!

**Comment by maieul** [comment]
de rien. Je vais envoyer le fichier sur le CTAN. Dans 2-3 jours utilisez texlive utility pour mettre � jour votre installation, puis supprimer le fichier .sty local

**Comment by Carolina1234** [comment]
Ya lo he hecho! Soy muy inquieta no me gusta tener ficheros sueltos por ahí dando vueltas así que hasta que no lo he encontrado su sitio no he parado. Mil gracias de nuevo.
