### ISSUE TITLE
Spurious unit punctuation with empty sourcedivison

### ISSUE THREAD

**Issue by moewew** [maieul/biblatex-source-division#2]
This came up in https://tex.stackexchange.com/q/390366/35864

Consider
```
\documentclass{article}

\usepackage[style=verbose-trad1, backend=biber, ibidpage]{biblatex}
\usepackage{biblatex-source-division}

\renewcommand*\newunitpunct{\addcomma\space}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite[3]{sigfridsson}

\cite[3]{sigfridsson}
\end{document}
```

The second citation comes out with a spurious comma for me:
> ibid.,

I think I have narrowed this down to
https://github.com/maieul/biblatex-source-division/blob/0b7d7c6c9881947a01f92b2e2e050ae90dd78f1e/biblatex-source-division.sty#L42-L53
The problem only occurs if no source division is given in the postnote argument. This causes `\titleaddon` to be empty. Then `\restorefield{titleaddon}{\titleaddon}` makes `titleaddon` an empty field. Note that while the field is empty, it is not undefined (`\iffieldundef{titleaddon}` is false). Now `biblatex` has little guards against empty fields (it checks for undefined fields and empty field formats, but not if the field itself is empty, presumably because Biber does not pass empty fields on). `\printfield{titleaddon}` in this case will print nothing, but it will trigger the punctuation tracker to act as though something was printed. This is why we get to see the comma.
You can see the difference between an empty field and an undefined field if you add 
```
\DeclareFieldFormat{titleaddon}{\mkbibparens{#1}}
\AtEveryCitekey{\printfield[parens]{foo}}
```
to the MWE the first line will cause an empty pair of parentheses to occur, while the second does nothing.

I could fix this temporarily by adding `\ifdefempty{\titleaddon}` checks, but that might not be the best solution.

BTW: Maybe you could give the macros `\titleaddon` and `\postnote` a more private name like `\blxsd@titleaddon` and `\blxsd@postnote` where `blxsd` stands for `biblatex-source-division`. That avoids name clashes

**Comment by maieul** [comment]
I have added the `\ifdefempty` test, which seems me the best way.
I have also modified the macro names.

Please try branch issue2

(The bug only appears with ibidpage… which I don’t use).

**Comment by moewew** [comment]
Brilliant thank you. I have pulled from `issue2` and I get the expected output in the MWE posted here as well as in the example from https://tex.stackexchange.com/a/390720/.

It really needed some work to get the issue to appear.

**Comment by maieul** [comment]
I have only done what you suggested ;-)

I will publish it tonight, while cooking ;-)
